### ISSUE TITLE
Add a mention of using empty Array literals for OptionSetType

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#12]
In code reviews I've seen occurrences where a function parameter requires a OptionSetType, to signify "no" options the author will pass in 0 as the rawValue in the type's initializer. We should make use of `OptionSetType`'s conformance to `ArrayLiteralConvertible` (via `SetAlgebraType`) and pass in `[]` instead.

Example:

Given:

``` swift
struct PackagingOptions : OptionSetType {
    let rawValue: Int
    init(rawValue: Int) { self.rawValue = rawValue }
    static let Box = PackagingOptions(rawValue: 1)
    static let Carton = PackagingOptions(rawValue: 2)
}

let options = PackagingOptions.Box
func placeOrder(orderId: String, options: PackagingOptions) { ... }
```

**Dont:**

``` swift
placeOrder("1234", options: PackagingOptions(rawValue: 0))
```

**Do:**

``` swift
placeOrder("1234", options: [])
```

**Comment by aenewton** [comment]
I didn't even know the `rawValue` method was a legal way of doing that.
