### ISSUE TITLE
Comment Style

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#14]
The current comment section leaves a bit to be desired, and provides no guidance for how to format these.

``` swift
/***************************
We obviously want to avoid these
***************************/
```

Things that we can steal from or just link to for the time being:
- [Swift's Markdown dialect](http://nshipster.com/swift-documentation/)
- [Some information from Apple on the subject](https://swift.org/documentation/api-design-guidelines/). ("Write a documentation comment for every declaration." is likely too much to ask, unless you are writing an API, but this has some good bits)
- [NSHipster](http://nshipster.com/swift-documentation/) on (This will become outdated moreso than the above links of course)

**Comment by eriklamanna** [comment]
So Xcode 8 does the following:

```
    /// <#Description#>
    ///
    /// - parameter json: <#json description#>
    ///
    /// - throws: <#throws value description#>
    ///
    /// - returns: <#return value description#>
```

**Comment by eriklamanna** [comment]
the docs say to use /*\* instead
