### ISSUE TITLE
Optional var initialization

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#15]
✅:

``` swift
class Person {
    var name: String?
}
```

🚫:

``` swift
class Person {
    var name: String? = nil
}
```

Thoughts?

**Comment by aenewton** [comment]
I agree wholeheartedly.

**Comment by mrketchup** [comment]
If you go with

``` swift
var name: String?
```

won't you have to set it `nil` in an initializer?

**Comment by rothomp3** [comment]
Nope, that's handled automatically by the compiler. It assumes that's what you want to do and does it for you, in other words.

**Comment by Grigs-b** [comment]
```
class Foo {
    var test: String?
}
```

Compiles just fine

**Comment by mattyohe** [comment]
As was mentioned in #6, this would also include locals or just vars of any kind.
