### ISSUE TITLE
Labeling associated values

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#17]
> I'm wondering if maybe a good general rule is for custom types that are intuitive, you can leave associated values unlabeled, e.g. case authenticated(User); but perhaps with Foundation types that are more generic add labels, e.g. case authenticated(username: String).

https://github.com/willowtreeapps/aviato-ios/pull/55#discussion_r78001753

**Comment by benfrye** [comment]
Fixed in PR #32
