### ISSUE TITLE
Add section that describes how void closures should be represented

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#2]
Discussion here:
https://willowtree.slack.com/archives/swift/p1441898332000006

``` swift
​() -> ()​
```

or

``` swift
 Void -> Void
```

**Comment by mrketchup** [comment]
or 

``` swift
() -> Void
```

**Comment by eriklamanna** [comment]
So from discussion and slack channel it appears that Apple uses () -> Void so I think that should be our preferred declaration.
