### ISSUE TITLE
Location of variable binding introducers (let/var) for enumerations

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#30]
Given:

``` swift
enum Foo {
  case bar(Bool)
  case baz(Bool)
}
```

**Single binding:**

A.

``` swift
case let .bar(qux)
```

B.

``` swift
case .bar(let qux)
```

**Multiple binding:**
C.

``` swift
case let (.bar(qux), .baz(quux))
```

D.

``` swift
case (.bar(let qux), .baz(let quux))
```

**Mixed multiple binding:**
E.

``` swift
case (.bar(let qux), .baz(var quux))
```

**Comment by mattyohe** [comment]
I'm partial to A. until I am forced in a mixed case to use E.

**Comment by aenewton** [comment]
I prefer B. Consider something like this: 

``` swift
enum Foo {
    case bar
    case baz(Bool)
}
```

Using `let` only makes sense in the context of cases that actually have associated values, so it feels more accurate to move that into the case itself. 

``` swift
case .baz(let qui)
```

**Comment by mattyohe** [comment]
@hpwooten Ah, so you point to cases I didn't consider.

``` swift
enum Foo {
  case bar
  case baz(Bool)
  case fred(Bool)
}
```

F. 

``` swift
case (.bar, .baz(let quux))
```

G. 

``` swift
case let (.bar, .baz(quux))
```

H. 

``` swift
case let (.bar, .baz(quux), .fred(corge))
```

I.

``` swift
case (.bar, .baz(let quux), .fred(let corge))
```

J.

``` swift
case (.bar, .baz(let quux), .fred(var corge))
```

Consistent with my previous comment, I'd go with G or H until the mixed binding case where I'd use J

**Comment by mattyohe** [comment]
After some in-person conversations, and some folks on Slack, I'm now being convinced against my initial thoughts. That is, prefer B, D, E, F, I, J.

Reason being, I'm really more looking for a simple rule to follow when this comes up and just simply stating, "place the introducer next to the variable being bound" is much simpler than trying to describe any other method.
