### ISSUE TITLE
What is our guideline for loop labels?

### ISSUE THREAD

**Issue by kconner** [willowtreeapps/swift-style-guide#37]
As in,

```swift
outer: for section in table {
    for item in section {
        if so-and-so {
            // Do some work, then
            break outer
        }
    }
}
```

Do we have a guideline for naming and casing `outer` here?

**Comment by ianterrell** [comment]
semantically meaningful if possible, as with all names. I don't think this needs any guidelines.

**Comment by kconner** [comment]
Is there a standard casing for these? Camel?

**Comment by ianterrell** [comment]
Swift language guide uses camel: https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/ControlFlow.html

(search for `gameLoop`)

**Comment by kconner** [comment]
I guess this is all obvious enough. No guideline is fine.
