### ISSUE TITLE
Don't initialize optionals in the nil case

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#6]
Not sure there's benefit to initializing optional types with nil.

:+1: 

``` swift
var foo: Foo?
```

:-1: 

``` swift
var foo: Foo? = nil
```

Objections?

**Comment by ianterrell** [comment]
:+1: especially for parity with the equivalent `let` case, for which a `nil` initialization at that level makes no sense.

**Comment by ianterrell** [comment]
Closing in favor of the newer, hipper https://github.com/willowtreeapps/swift-style-guide/issues/15

**Comment by mattyohe** [comment]
Lol thanks... I'm forgetting what I've written :cry: 

Probably need to start writing some PRs to close these! :smile:
