### ISSUE TITLE
Emphasize use of for-in style loops

### ISSUE THREAD

**Issue by aenewton** [willowtreeapps/swift-style-guide#7]
The guide currently recommends to use `for-in` style loops as opposed to `for-conditional-increment`. It may be beneficial to note that the latter style will be disallowed in Swift 3, and will therefore become a requirement and not a suggestion. 

https://github.com/apple/swift-evolution/blob/master/proposals/0007-remove-c-style-for-loops.md

**Comment by mattyohe** [comment]
Do we want to just kill the current [suggestion](https://github.com/willowtreeapps/swift-style-guide#control-flow) then?

**Comment by aenewton** [comment]
That might be best
