### ISSUE TITLE
Guard against third party unannotated methods

### ISSUE THREAD

**Issue by mattyohe** [willowtreeapps/swift-style-guide#8]
Third party libraries that have yet to annotate their headers for nullability will be imported into swift with IUO.

We should treat these as optionals and guard as we would any other optionals.

Example. A third party library that gets imported might look to swift as:

``` swift
public class ThirdPartyDelegate : NSObject {
    public func onError(errorInfo: ErrorInfo!)
}
```

An implementing subclass should:

``` swift
public class MyDelegate: ThirdPartyDelegate {
    override public func onError(errorInfo: ErrorInfo?) {
        logger.error("[ERROR] ThirdPartyDelegate: \(errorInfo?.message)")
    }
}
```

Specifically, note changing the type of ErrorInfo from `ErrorInfo!` to `ErrorInfo?`

**Comment by ianterrell** [comment]
:+1:
